apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-map
data:
  DB_USERNAME: myuser
  DB_HOST: 127.0.0.1
  DB_PORT: '5432'
  DB_NAME: mydatabase
---
apiVersion: v1
kind: Secret
metadata:
  name: mypassword
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==